### ISSUE TITLE
test with WordPress 4.2

### ISSUE THREAD

**Issue by joehobson** [navnorth/wp-stories-posts#1]
Same issue as on the wp-oer plugin (https://github.com/navnorth/wp-oer/issues/13), particularly with the taxonomies. Make sure you add content (stories) using WP 4.1 and then upgrade to WP 4.2 so that you can see how pre-existing content is handled in the migration.

**Comment by johnpaulbalagolan** [comment]
Forgot to left message here after my testing. I have tested the WP Stories plugin even going back to WP 4.0 but I found no issue with it. I even installed Shared terms and editing some taxonomies or tags but it was handled well by WordPress. Though, I was testing it with fresh install from 4.0 and adding the stories and posts simultaneously including the categories, characteristics, programs that are the same. Do we have a copy of live data this plugin is used from. This might be helpful to cover live data for testing.

Fyi. Thanks.
